# Generated by Django 3.2.9 on 2021-12-03 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotewallapi', '0002_rename_createdon_group_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member', through='quotewallapi.UserGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
