# Generated by Django 3.2.10 on 2021-12-11 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotewallapi', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requests',
            field=models.ManyToManyField(related_name='requesting_to_join', through='quotewallapi.ApprovalRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_of', through='quotewallapi.UserGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
