# Generated by Django 3.2.10 on 2021-12-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotewallapi', '0004_auto_20211211_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(max_length=75),
        ),
    ]
