# Generated by Django 3.2.10 on 2021-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotewallapi', '0005_auto_20211216_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.TextField(),
        ),
    ]
