# Generated by Django 3.2.10 on 2021-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotewallapi', '0006_auto_20211216_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(max_length=100),
        ),
    ]
